services:
  open-plaato-keg:
    image: ghcr.io/darkjaeger/open-plaato-keg:latest
    container_name: open-plaato-keg
    ports:
      - "1234:1234"
      - "8085:8085"
    volumes:
      - keg-db:/db
    environment:
      - DATABASE_FILE_PATH=/db/keg_data.bin
    restart: always

  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "8080:8080"
    environment:
      - WATCHTOWER_POLL_INTERVAL=86400
      - WATCHTOWER_CONTAINER_NAMES=open-plaato-keg
      - WATCHTOWER_HTTP_API_UPDATE=true
      - WATCHTOWER_HTTP_API_TOKEN=openplaato-watchtower-2026
    restart: always

volumes:
  keg-db:
